[pytest]
testpaths = tests
python_files = test_*.py
qt_api = pyside6
filterwarnings =
    error
    ignore::pyparsing.warnings.PyparsingDeprecationWarning
    ignore::sklearn.exceptions.ConvergenceWarning
