from setuptools import setup, find_packages
version="2.0.3"
setup(
    name="robert",
    packages=find_packages(exclude=["tests"]),
    package_data={"robert": ["model_params/*","report/*","icons/*"]},
    version=version,
    license="MIT",
    description="Refiner and Optimizer of a Bunch of Existing Regression Tools",
    long_description="Documentation in Read The Docs: https://robert.readthedocs.io",
    long_description_content_type="text/markdown",
    author="Juan V. Alegre Requena, David Dalmau",
    author_email="jv.alegre@csic.es",
    keywords=[
        "workflows",
        "machine learning",
        "cheminformatics",
        "data curation",
        "prediction",
        "automated",
    ],
    url="https://github.com/jvalegre/robert",
    download_url=f"https://github.com/jvalegre/robert/archive/refs/tags/{version}.tar.gz",
    classifiers=[
        "Development Status :: 5 - Production/Stable",  # Chose either "3 - Alpha", "4 - Beta" or "5 - Production/Stable" as the current state of your package
        "Intended Audience :: Developers",  # Define that your audience are developers
        "Topic :: Software Development :: Build Tools",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.11",  # Specify which python versions you want to support
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
    ],
    install_requires=[
        "PyYAML==6.0.3",
        "matplotlib==3.10.0",
        "pandas==2.3.3",
        "numpy==2.3.4",
        "progress==1.6.1",
        "seaborn==0.13.2",
        "scipy==1.15.0",
        "scikit-learn==1.7.2",
        "bayesian-optimization==3.1.0",
        "numba==0.62.1",
        "shap==0.49.1",
        "weasyprint==63.1",
        "PySide6==6.9.2",
        "PyMuPDF",
        "ansi2html",
        "rdkit==2025.9.1",
        "psutil==7.0.0",
        "requests==2.32.5",
    ],
    python_requires=">=3.11",
    include_package_data=True,
)
