#!/usr/bin/env python

######################################################.
# 	        Testing VERIFY with pytest 	             #
######################################################.

import os
import sys
import glob
import pytest
import shutil
import subprocess
from pathlib import Path
from robert.verify import verify

# saves the working directory
path_main = os.getcwd()
path_verify = os.path.join(path_main, "VERIFY")


# VERIFY tests
@pytest.mark.parametrize(
    "test_job",
    [
        ("clas"),  # test for clasification
        ("standard"),  # standard test
        ("standard_cmd"),  # standard test with command line
    ],
)
def test_VERIFY(test_job):
    # leave the folders as they were initially to run a different batch of tests
    if os.path.exists(path_verify):
        shutil.rmtree(path_verify)
        # remove DAT and CSV files generated by VERIFY
        dat_files = glob.glob("*.dat")
        for dat_file in dat_files:
            if "VERIFY" in dat_file:
                os.remove(dat_file)

    if test_job == "clas":  # rename folders to use in classification
        # rename the regression GENERATE folder
        filepath_reg = Path(path_main) / "GENERATE"
        filepath_reg.rename(Path(path_main) / "GENERATE_reg")
        # rename the classification GENERATE folder
        filepath = Path(path_main) / "GENERATE_clas"
        filepath.rename(Path(path_main) / "GENERATE")

    else:  # in case the clas test fails and the ending rename doesn't happen
        if os.path.exists(Path(path_main) / "GENERATE_reg"):
            # rename the classification GENERATE folder
            filepath = Path(path_main) / "GENERATE"
            filepath.rename(Path(path_main) / "GENERATE_clas")
            # rename the regression GENERATE folder
            filepath_reg = Path(path_main) / "GENERATE_reg"
            filepath_reg.rename(Path(path_main) / "GENERATE")

    # runs the program with the different tests
    if test_job == "standard_cmd":
        cmd_robert = [
            sys.executable,
            "-m",
            "robert",
            "--verify",
        ]

        subprocess.run(cmd_robert)

    else:
        verify_kwargs = {}

        verify(**verify_kwargs)

    # check that the DAT file is created
    assert not os.path.exists(os.path.join(path_main, "VERIFY_data.dat"))
    outfile = open(os.path.join(path_verify, "VERIFY_data.dat"), "r")
    outlines = outfile.readlines()
    outfile.close()
    assert "ROBERT v" in outlines[0]
    results_line, start_reading = False, False
    for i, line in enumerate(outlines):
        if (
            "------- Starting model with PFI filter " in line
        ):  # focus on the PFI since there is an unclear test
            start_reading = True
        if start_reading:
            if "Results of flawed models and sorted cross-validation:" in line:
                results_line = True
                if test_job == "clas":
                    assert (
                        "Original MCC (10x 5-fold CV) 0.56 - 15% & 30% threshold = 0.48 & 0.39"
                        in outlines[i + 1]
                    )
                    assert (
                        "o y_mean: PASSED, MCC = 0.0, lower than thresholds"
                        in outlines[i + 2]
                    )
                    assert (
                        "o y_shuffle: PASSED, MCC = -0.17, lower than thresholds"
                        in outlines[i + 3]
                    )
                    assert (
                        "x onehot: FAILED, MCC = 0.59, higher than thresholds"
                        in outlines[i + 4]
                    )
                    assert (
                        "o cluster: PASSED, MCC = 0.0, lower than thresholds"
                        in outlines[i + 5]
                    )
                    assert (
                        "- Sorted CV : Accuracy = [0.88, 0.88, 0.86, 0.57, 1.0], F1 score = [0.89, 0.89, 0.89, 0.4, 1.0], MCC = [0.77, 0.77, 0.73, 0.35, 1.0]"
                        in outlines[i + 6]
                    )
                elif test_job == "standard":
                    assert (
                        "Original RMSE (10x 5-fold CV) 0.31 + 15% & 30% threshold = 0.36 & 0.4"
                        in outlines[i + 1]
                    )
                    assert "o y_mean: PASSED, RMSE = 0.7" in outlines[i + 2]
                    assert "o y_shuffle: PASSED, RMSE = 0.97" in outlines[i + 3]
                    assert "o onehot: PASSED, RMSE = 0.53" in outlines[i + 4]
                    assert "o cluster: PASSED, RMSE = 0.49" in outlines[i + 5]
                    assert (
                        "- Sorted 5-fold CV : R2 = [0.15, 0.66, 0.16, 0.34, 0.17], MAE = [0.49, 0.19, 0.25, 0.37, 0.41], RMSE = [0.5, 0.25, 0.32, 0.44, 0.47]"
                        in outlines[i + 6]
                    )
                break
    assert results_line

    # check that the verify plots and DAT file are created
    assert len(glob.glob(os.path.join(path_verify, "*.png"))) == 2
    assert len(glob.glob(os.path.join(path_verify, "*.dat"))) == 1

    if test_job == "clas":  # rename folders back to their original names
        # rename the classification GENERATE folder
        filepath = Path(path_main) / "GENERATE"
        filepath.rename(Path(path_main) / "GENERATE_clas")
        # rename the regression GENERATE folder
        filepath_reg = Path(path_main) / "GENERATE_reg"
        filepath_reg.rename(Path(path_main) / "GENERATE")
