#!/usr/bin/env python

######################################################.
# 	        Testing GENERATE with pytest 	         #
######################################################.

import ast
import json
import os
import sys
import glob
import pytest
import shutil
import subprocess
import pandas as pd
from pathlib import Path
from robert.generate import generate
from tests.platform_goldens import (
    GENERATE_STANDARD_RMSE,
    log_line_metric_close,
    platform_key,
)

# saves the working directory (os.path.join keeps paths valid on Windows and Linux)
path_main = os.getcwd()
path_generate = os.path.join(path_main, "GENERATE")


def _read_best_model_pair(best_dir):
    """Load the params CSV and its *_db.csv pair; glob order is filesystem-dependent."""
    paths = glob.glob(os.path.join(best_dir, "*.csv"))
    assert len(paths) == 2
    db_paths = [p for p in paths if os.path.basename(p).endswith("_db.csv")]
    params_paths = [p for p in paths if p not in db_paths]
    assert len(db_paths) == 1 and len(params_paths) == 1
    return pd.read_csv(params_paths[0], encoding="utf-8"), pd.read_csv(
        db_paths[0], encoding="utf-8"
    )


def _model_tag(test_job):
    """ML model name for single-model GENERATE test jobs."""
    return {
        "reduced_gp": "GP",
        "reduced_adab": "ADAB",
        "reduced_xgb": "XGB",
        "reduced_vr": "VR",
        "reduced_vr_clas": "VR",
        "reduced_clas": "RF",
    }.get(test_job, "RF")


def _read_model_pair(generate_dir, folder, model, *, pfi=False):
    """Load params and *_db.csv for a specific model under Raw_data."""
    suffix = f"{model}_PFI" if pfi else model
    params_path = os.path.join(generate_dir, "Raw_data", folder, f"{suffix}.csv")
    db_path = os.path.join(generate_dir, "Raw_data", folder, f"{suffix}_db.csv")
    assert os.path.isfile(params_path), params_path
    assert os.path.isfile(db_path), db_path
    return pd.read_csv(params_path, encoding="utf-8"), pd.read_csv(
        db_path, encoding="utf-8"
    )


# Expected descriptors per model for the standard multi-model job
_STANDARD_MODEL_DESCS = {
    "No_PFI": {
        "RF": ["x10", "x2", "x5", "x7", "x9"],
        "GB": [
            "Csub-Csub",
            "Csub-H",
            "H-O",
            "x10",
            "x11",
            "x2",
            "x5",
            "x7",
            "x8",
            "ynoise",
        ],
        "NN": [
            "Csub-Csub",
            "Csub-H",
            "H-O",
            "x10",
            "x11",
            "x2",
            "x5",
            "x7",
            "x8",
            "x9",
            "ynoise",
        ],
        "MVL": [
            "Csub-Csub",
            "Csub-H",
            "H-O",
            "x10",
            "x11",
            "x2",
            "x5",
            "x7",
            "x8",
            "x9",
            "ynoise",
        ],
    },
    "PFI": {
        "RF": ["x10", "x7"],
        "GB": ["x10", "x7"],
        "NN": ["x10", "x2", "x5", "x7", "x8", "x9"],
        "MVL": ["Csub-Csub", "Csub-H", "H-O", "x10", "x7", "x9"],
    },
}


def _parse_x_descriptors(raw):
    """Parse X_descriptors from GENERATE CSV (JSON or Python literal list)."""
    text = raw if isinstance(raw, str) else str(raw)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return ast.literal_eval(text)


# GENERATE tests
@pytest.mark.parametrize(
    "test_job",
    [
        ("reduced"),  # test with less models and partition sizes
        ("reduced_cmd"),  # reduced test through cmd line
        ("reduced_noPFI"),  # test to disable the PFI analysis
        ("reduced_PFImax"),  # test to select the number of PFI features
        ("reduced_kfold"),  # test with different kfold and repetitions
        (
            "reduced_gp"
        ),  # test for other GP model (important since PFI filter gives different results compared to standard)
        (
            "reduced_adab"
        ),  # test for other GP model (important since PFI filter tries to discard all the descriptors)
        ("reduced_xgb"),  # test for XGB model (tree booster with feature importances)
        ("reduced_vr"),  # test for Voting Regressor model
        ("reduced_vr_clas"),  # test Voting Classifier workflow
        ("reduced_clas"),  # test for clasification models
        ("standard"),  # standard test
    ],
)
def test_GENERATE(test_job):
    # leave the folders as they were initially to run a different batch of tests
    if os.path.exists(path_generate):
        shutil.rmtree(path_generate)
        # remove DAT and CSV files generated by GENERATE
        dat_files = glob.glob("*.dat")
        for dat_file in dat_files:
            if "GENERATE" in dat_file:
                os.remove(dat_file)
    if test_job == "reduced_clas" and os.path.exists(
        os.path.join(path_main, "GENERATE_clas")
    ):
        shutil.rmtree(os.path.join(path_main, "GENERATE_clas"))

    # runs the program with the different tests
    if test_job in ["reduced_clas", "reduced_vr_clas"]:
        csv_name = os.path.join("tests", "Robert_example_clas.csv")
    else:
        csv_name = os.path.join("CURATE", "Robert_example_CURATE.csv")

    if test_job == "reduced_cmd":
        cmd_robert = [
            sys.executable,
            "-m",
            "robert",
            "--generate",
            "--csv_name",
            csv_name,
            "--y",
            "Target_values",
            "--model",
            "[RF]",
            "--init_points",
            "1",
            "--n_iter",
            "1",
        ]
        subprocess.run(cmd_robert)
    else:
        generate_kwargs = {"generate": True, "csv_name": csv_name, "y": "Target_values"}
        if test_job != "standard":
            # add model
            if test_job not in [
                "reduced_gp",
                "reduced_adab",
                "reduced_xgb",
                "reduced_vr",
                "reduced_vr_clas",
            ]:
                generate_kwargs["model"] = ["RF"]
            elif test_job == "reduced_gp":
                generate_kwargs["model"] = ["GP"]
            elif test_job == "reduced_adab":
                generate_kwargs["model"] = ["Adab"]
            elif test_job == "reduced_xgb":
                generate_kwargs["model"] = ["XGB"]
            elif test_job in ["reduced_vr", "reduced_vr_clas"]:
                generate_kwargs["model"] = ["VR"]

            # adjust cmd for tests
            if test_job == "reduced_noPFI":
                generate_kwargs["pfi_filter"] = False
            elif test_job == "reduced_PFImax":
                generate_kwargs["pfi_max"] = 1
            elif test_job == "reduced_kfold":
                generate_kwargs["kfold"] = 10
                generate_kwargs["repeat_kfolds"] = 5
            elif test_job in ["reduced_clas", "reduced_vr_clas"]:
                generate_kwargs["type"] = "clas"

            generate_kwargs["init_points"] = 1
            generate_kwargs["n_iter"] = 1

        else:  # needed to define the variables, change if default options change
            generate_kwargs["model"] = ["RF", "GB", "NN", "MVL"]
            generate_kwargs["init_points"] = 2
            generate_kwargs["n_iter"] = 2

        generate(**generate_kwargs)

    if test_job not in []:
        # check that the DAT file is created
        assert not os.path.exists(os.path.join(path_main, "GENERATE_data.dat"))
        outfile = open(os.path.join(path_generate, "GENERATE_data.dat"), "r")
        outlines = outfile.readlines()
        outfile.close()
        assert "ROBERT v" in outlines[0]
        if test_job == "reduced_cmd":
            indeces = [9, 10, 11, 12]
        else:
            indeces = [7, 8, 9, 10]
        assert "- 37 datapoints" in outlines[indeces[0]]
        if test_job in ["reduced_clas", "reduced_vr_clas"]:
            assert "- 9 accepted descriptors" in outlines[indeces[1]]
        else:
            assert "- 11 accepted descriptors" in outlines[indeces[1]]
        assert "- 1 ignored descriptors" in outlines[indeces[2]]
        assert "- 0 discarded descriptors" in outlines[indeces[3]]

        # find GENERATE evaluation
        finding_line = 0
        reproducibility = 0
        finding_changed_kfold = 0
        for line in outlines:
            if (
                "o Starting BO-based hyperoptimization using the combined target:"
                in line
            ):
                finding_line += 1
            elif "1. 50% = RMSE from a 10x repeated 5-fold CV (interpoplation)" in line:
                finding_line += 1
            elif (
                "2. 50% = RMSE from the bottom or top (worst performing) fold in a sorted 5-fold CV (extrapolation)"
                in line
            ):
                finding_line += 1
            elif (
                "o  Before hyperoptimization, 20% of the data (or 4 points at least) was separated as test set, using an even distribution of data points across the range of y values."
                in line
            ):
                finding_line += 0.5  # it appears two times, in PFI and no PFI
                # this elif adds 4 points to the standard test (0.5*2(PFI and no PFI)*4(models)
            elif log_line_metric_close(
                line,
                "o Best combined RMSE (target) found in BO for RF (no PFI filter):",
                0.45,
                rel_tol=0.05,
                abs_tol=0.02,
            ):
                reproducibility += 1
            elif log_line_metric_close(
                line,
                "o Combined RMSE for RF (with PFI filter):",
                0.41,
                rel_tol=0.05,
                abs_tol=0.02,
            ):
                reproducibility += 1
            # lines only for standard
            elif "- 1/4 - ML model: RF" in line:
                finding_line += 1
            elif "- 2/4 - ML model: GB" in line:
                finding_line += 1
            elif "- 3/4 - ML model: NN" in line:
                finding_line += 1
            elif "- 4/4 - ML model: MVL" in line:
                finding_line += 1
            elif any(
                log_line_metric_close(line, prefix, expected)
                for prefix, expected in GENERATE_STANDARD_RMSE[platform_key()].items()
            ):
                reproducibility += 1
            elif "1. 50% = RMSE from a 5x repeated 10-fold CV (interpoplation)" in line:
                finding_changed_kfold += 1

        if test_job == "reduced_noPFI":
            assert finding_line == 3.5
            assert reproducibility == 1
        elif test_job in ["reduced", "reduced_cmd", "reduced_vr"]:
            assert finding_line == 4
            if test_job in ["reduced", "reduced_cmd"]:
                assert reproducibility == 2
            else:
                assert reproducibility == 0
        if test_job == "standard":
            assert finding_line == 11
            assert reproducibility == 8
        if test_job == "reduced_kfold":
            assert finding_changed_kfold == 1

        # check that the right amount of CSV files were created
        if test_job == "reduced_cmd":
            expected_amount = 2
        else:
            expected_amount = len(generate_kwargs["model"]) * 2
        if test_job != "reduced_noPFI":
            folders = ["No_PFI", "PFI"]
        else:
            folders = ["No_PFI"]
            assert not os.path.exists(os.path.join(path_generate, "Raw_data", "PFI"))

        for folder in folders:
            csv_amount = glob.glob(
                os.path.join(path_generate, "Raw_data", folder, "*.csv")
            )
            assert expected_amount == len(csv_amount)

            _read_best_model_pair(os.path.join(path_generate, "Best_model", folder))

            if test_job == "standard":
                model_descs = _STANDARD_MODEL_DESCS[folder]
            elif test_job in [
                "reduced",
                "reduced_cmd",
                "reduced_PFImax",
                "reduced_gp",
                "reduced_adab",
                "reduced_xgb",
                "reduced_clas",
            ]:
                model = _model_tag(test_job)
                if folder == "No_PFI":
                    if test_job in ["reduced", "reduced_cmd", "reduced_PFImax"]:
                        desc_list = ["x10", "x2", "x5", "x7", "x9"]
                    elif test_job == "reduced_gp":
                        desc_list = [
                            "Csub-Csub",
                            "Csub-H",
                            "H-O",
                            "x10",
                            "x11",
                            "x2",
                            "x5",
                            "x7",
                            "x8",
                            "x9",
                            "ynoise",
                        ]
                    elif test_job in ["reduced_xgb", "reduced_adab"]:
                        desc_list = [
                            "Csub-Csub",
                            "Csub-H",
                            "H-O",
                            "x10",
                            "x11",
                            "x2",
                            "x5",
                            "x7",
                            "x8",
                            "x9",
                            "ynoise",
                        ]
                    elif test_job == "reduced_clas":
                        desc_list = [
                            "x1",
                            "x10",
                            "x2",
                            "x3",
                            "x5",
                            "x6",
                            "x7",
                            "x8",
                            "x9",
                        ]
                elif folder == "PFI":
                    if test_job in ["reduced", "reduced_cmd"]:
                        desc_list = ["x7", "x10"]
                    elif test_job == "reduced_PFImax":
                        desc_list = ["x10"]
                    elif test_job == "reduced_gp":
                        desc_list = ["x5", "Csub-Csub", "x7", "x10", "x8", "Csub-H"]
                    elif test_job == "reduced_xgb":
                        desc_list = ["x10", "x5", "x7"]
                    elif test_job == "reduced_adab":
                        desc_list = ["x10", "x9"]
                    elif test_job == "reduced_clas":
                        desc_list = ["x6"]
                model_descs = {model: desc_list}
            else:
                model_descs = {}

            for model, desc_list in model_descs.items():
                params_best, db_best = _read_model_pair(
                    path_generate, folder, model, pfi=(folder == "PFI")
                )

                if test_job in ["reduced", "reduced_cmd"] and model == "RF":
                    expected_sets = [
                        "Training",
                        "Training",
                        "Training",
                        "Test",
                        "Training",
                    ]
                    for i, expected_set in enumerate(expected_sets):
                        assert db_best["Set"][i] == expected_set
                    expected_rows = [
                        0.308776518,
                        0.321084552,
                        0.329517076,
                        0.39762592,
                        0.410599034,
                    ]
                    assert list(
                        db_best["Target_values"][: len(expected_rows)]
                    ) == pytest.approx(expected_rows, rel=1e-5, abs=1e-8)
                    expected_cols = ["x10", "x2", "x5", "x7", "x9"]
                    for i, expected_col in enumerate(expected_cols):
                        assert db_best.columns[i] == expected_col

                stored_descs = _parse_x_descriptors(params_best["X_descriptors"][0])
                for var in desc_list:
                    assert var in stored_descs
                assert len(desc_list) == len(stored_descs)

                if test_job == "reduced_clas":
                    metric_bo = "mcc"
                else:
                    metric_bo = "rmse"

                for col in [
                    "model",
                    "type",
                    "kfold",
                    "repeat_kfolds",
                    "seed",
                    "error_type",
                    "y",
                    "names",
                    "X_descriptors",
                    "params",
                    f"combined_{metric_bo}",
                    "split",
                ]:
                    assert col in params_best.columns

                if test_job == "reduced_clas":
                    assert params_best["split"][0].upper() == "RND"
                elif test_job != "standard":
                    assert params_best["split"][0].upper() == "EVEN"

        # check that the heatmap plots were generated
        assert os.path.exists(
            os.path.join(path_generate, "Raw_data", "Heatmap_ML_models_No_PFI.png")
        )
        if test_job != "reduced_noPFI":
            assert os.path.exists(
                os.path.join(path_generate, "Raw_data", "Heatmap_ML_models_PFI.png")
            )
        else:
            assert not os.path.exists(
                os.path.join(path_generate, "Raw_data", "Heatmap_ML_models_PFI.png")
            )

        # Check that the default metric for classification models is MCC
        if test_job in ["reduced_clas", "reduced_vr_clas"]:
            model_name = "RF" if test_job == "reduced_clas" else "VR"
            csv_clas = glob.glob(
                os.path.join(
                    path_generate, "Best_model", "PFI", f"{model_name}_PFI.csv"
                )
            )
            df = pd.read_csv(csv_clas[0])
            if "error_type" in df.columns:
                error_types = df["error_type"].tolist()
            assert "mcc" in error_types

    if test_job == "reduced_clas":
        filepath = Path(path_generate)
        filepath.rename(Path(os.path.join(path_main, "GENERATE_clas")))
